- hosts: all
  tasks:
  - name: "Create wallbutton user"
    user:
      name: wallbutton
      shell: '/bin/bash'
      groups: dialout,gpio
  - name: ansible set permission recursvely for a directory
    file:
      path: /home/wallbutton/bin
      state: directory
      owner: wallbutton
      group: wallbutton
  - name: Copy systemd service file
    copy:
      src: systemd/wallbutton.service
      dest: /etc/systemd/system/wallbutton.service
      owner: root
      group: root
      mode: '0644'
  - name: Copy .py files
    copy:
      src: py3/{{item}}
      dest: /home/wallbutton/bin/{{item}}
      mode: u=rw+x,g=r,o=r
      owner: wallbutton
      group: wallbutton
    loop:
        - 'denon.py'
        - 'gipo_button.py'
        - 'hue.py'
        - 'config.py'
  - name: Install acl #required for become_user
    package:
      name: acl
      state: present
  - name: Install phue
    become: true
    become_user: wallbutton
    pip:
      name: phue
      extra_args: --user
      state: present
      executable: pip3
  - name: Install unattended-upgrades
    package:
      name: unattended-upgrades
      state: present
  - name: Copy 20auto-upgrades
    copy:
      src: rpi/debian-20auto-upgrades
      dest: /etc/apt/apt.conf.d/debian-20auto-upgrades
      owner: root
      group: root
      mode: '0644'
  - name: Copy modprobe.d/blacklist.conf
    copy:
      src: rpi/blacklist.conf
      dest: /etc/modprobe.d/blacklist.conf
      owner: root
      group: root
      mode: '0644'
  - name: enable unattended-upgrades.service
    systemd:
      name: unattended-upgrades
      state: restarted
      enabled: yes
  - name: disable rsyslog
    systemd:
      name: rsyslog.service
      state: stopped
      enabled: no
  - name: enable wallbutton.service
    systemd:
      name: wallbutton.service
      state: restarted
      enabled: yes
